config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  scope '/admin' do
    resources :collections
    resources :users do
      get 'edit_password', on: :member
      put 'update_password', on: :member
    end
    resources :orders do
      get 'complete', on: :member
      get 'send_to_client', on: :member
    end
    resources :models, except: :destroy do
      get 'activate', on: :member
      get 'deactivate', on: :member
    end
    resources :brands, except: :destroy do
      get 'search_models', on: :member
      get 'activate', on: :member
      get 'deactivate', on: :member
    end
    resources :products, except: :destroy do
      get 'activate', on: :member
      get 'deactivate', on: :member
      resources :related_products, path: 'related'
      resources :similar_products, path: 'similar'
    end
    resources :pictures, only: [:create, :destroy]
    resources :sliders, only: [:index, :update]
    resources :slider_brands, only: [:index, :update]
    resources :banners, only: [:show, :update], param: :position
    resources :interior_builders, param: :position
    resources :offer_builders
    resources :newsletter_builders
  end
  root 'home#index'
  get 'brand/:id' => 'home#brand_section', as: :brand_section
  get 'marcas' => 'home#brands_section', as: :brands_section
  get 'models/:id' => 'home#model_section', as: :model_section
  get 'colecciones' => 'home#collections_section', as: :collections_section
  get 'coleccion/:id' => 'home#collection_section', as: :collection_section
  get 'lo_mas_nuevo' => 'home#newest_section', as: :newest_section
  get 'producto/:id' => 'home#product_section', as: :product_section
  get 'oferta' => 'home#offer_section', as: :offer_section
  get 'contactanos' => 'home#contact_section', as: :contact_section
  get 'search_section' => 'home#search_section', as: :search_section
  get 'make_contact' => 'home#make_contact', as: :make_contact
  get 'models_for_brand' => 'home#models_for_brand', as: :models_for_brand
  get 'products_for_model' => 'home#products_for_model', as: :products_for_model
  
  resources :newsletters, only: [:create, :index, :destroy]
  resources :customers, only: [:edit, :update]

  resources :carts do
    get 'checkout', on: :member
    get 'detail', on: :member
    get 'complete', on: :member
    resources :line_items
    get 'add_line_item', on: :member
    get 'remove_line_item', on: :member
  end

end

app/views/shared/_navigation_bar.html.haml
%nav.navbar-default.navbar-static-side{role: "navigation"}
  %div.sidebar-collapse
    %ul.nav#side-menu
      %li.nav-header
        %div.dropdown.profile-element
          %span
            = image_tag current_user.profile_picture, class: "img-circle"
          %a.dropdown-toggle{"data-toggle" => "dropdown", "href" => "#"}
            %span.clear
              %span.block.m-t-xs
                %strong.font-bold= current_user.complete_name
              %span.text-muted.text-xs.block= current_user.email 
        %div.logo-element= "IN+"
      %li{class: "#{set_active_class("order")}"}
        = link_to orders_path do
          %i.fa.fa-list-ul
          %span.nav-label= "Órdenes"
      %li{class: "#{set_active_class("product")}"}
        = link_to products_path do
          %i.fa.fa-th
          %span.nav-label= "Productos"
      %li{class: "#{set_active_class("user")}"}
        = link_to users_path do
          %i.fa.fa-users
          %span.nav-label= "Clientes"
      %li{class: "#{set_active_class("collection")}"}
        = link_to collections_path do
          %i.fa.fa-database
          %span.nav-label= "Colecciones / Categorías"
      %li{class: "#{set_active_class("model")}"}
        = link_to models_path do
          %i.fa.fa-mobile
          %span.nav-label= "Equipos"
      %li{class: "#{set_active_class("brand")}"}
        = link_to brands_path do
          %i.fa.fa-apple
          %span.nav-label= "Marcas"
      %li{class: "#{set_active_class("home")}"}
        = link_to "#" do
          %i.fa.fa-magic
          %span.nav-label= "Home"
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to "Slider Principal", sliders_path
          %li
            = link_to "Sección de Marcas", slider_brands_path
          %li
            = link_to "Primer Banner", banner_path("first")
          %li
            = link_to "Segundo Banner", banner_path("second")
          %li
            = link_to "Tercer Banner", banner_path("third")
          %li
            = link_to "Cuarto Banner", banner_path("fourth")

      %li{class: "#{set_active_class("builder")}"}
        = link_to "#" do
          %i.fa.fa-magic
          %span.nav-label= "Sección Nuevo"
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to "Primer Banner", interior_builder_path("first")
          %li
            = link_to "Segundo Banner", interior_builder_path("second")
      
      %li{class: "#{set_active_class("offer_builder")}"}
        = link_to offer_builders_path do
          %i.fa.fa-magic
          %span.nav-label= "Sección de Ofertas"
    
      %li{class: "#{set_active_class("newsletter_builder")}"}
        = link_to newsletter_builders_path do
          %i.fa.fa-magic
          %span.nav-label= "Modal Principal"

      %li{class: "#{set_active_class("newsletter")}"}
        = link_to newsletters_path do
          %i.fa.fa-magic
          %span.nav-label= "Sección de Newsletter"

app/views/shared/_navigation_bar_front.html.haml
.nav-container
  %a#top
  %nav
    .nav-utility
      .wp-info
        %p
          Búscanos en Whatsapp
          %i.fa.fa-whatsapp
          %a{href: ""} 818 645 321
          \/
          %a{href: ""} 818 645 321
    .nav-bar
      .module.left
        = link_to root_path do
          = image_tag("logo.jpg", alt: "Foundry", class: "logo logo-light")
          = image_tag("logo.jpg", alt: "Foundry", class: "logo logo-dark")
      .module.widget-handle.mobile-toggle.right.visible-sm.visible-xs.chops
        %i.ti-menu
      .module-group.right
        .module.left
          %ul.menu
            %li.has-dropdown
              = link_to "Mi Cel", "#"
              %ul.mega-menu
                - @brands.each do |brand|
                  %li
                    %ul
                      %li
                        %span.title= brand.name.titleize
                        - brand.models.each do |model|
                          %li
                            = link_to model.name.titleize, "#"
            %li.has-dropdown
              = link_to "Colecciones", "#"
              %ul.mega-menu
                - @collections.each do |collection_slide|
                  %li
                    - collection_slide.each do |collection|
                      %ul
                        %li
                          = link_to collection.name, "#"
            %li
              %a{:href => ""} Lo más nuevo
            %li
              %a{:href => ""} Oferta
            %li
              %a{:href => ""} Contáctanos
        / end of menu module
        .module.widget-handle.search-widget-handle.left
          .search
            %i.ti-search
            %span.title Search Site
          .function
            %form.search-form
              %input{placeholder: "Buscar", type: "text"}/
        .module.widget-handle.cart-widget-handle.left
          - if user_signed_in?
            = link_to "Logout", destroy_user_session_path, method: :delete
          - else
            = render "login"
            
        .module.widget-handle.cart-widget-handle.left
          %div
            %i.ti-panel
            %span.title Administrar Sitio
        .module.widget-handle.cart-widget-handle.left.vart
          .cart
            %i.ti-shopping-cart
            %span.label.number 2
            %span.title Shopping Cart
          .function
            .widget
              %h6.title Shopping Cart
              %hr
                %ul.cart-overview
                  %li
                    = link_to "#" do
                      = image_tag("01-demo-pic.jpg", alt: "Product")
                      .description
                        %span.product-title Canvas Backpack
                        %span.price.number $39.90
                  %li
                    = link_to "#" do
                      = image_tag("01-demo-pic.jpg", alt: "Product")
                      .description
                        %span.product-title Vintage Camera
                        %span.price.number $249.50
                %hr
                  .cart-controls
                    %a.btn.btn-sm.btn-filled.mr-hover{:href => "cart.html"} Cotizar
                    .list-inline.pull-right
                      %span.cart-total Total:
                      %span.number $289.40
            / end of widget
      / end of module group

app/views/shared/_picture_fields.html.haml
%label=image_label_for(object)
%div{class: "slide_container #{slider_class(object)}"}
  = image_tag(object.picture.image_url) if object.picture
= f.fields_for :picture do |f_fields|
  - if object.picture.persisted?
    = f_fields.file_field :image, class: "form-control"
  - else
    = f_fields.file_field :image, class: "form-control", required: true

app/views/shared/_script_template.html.erb
<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>