config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  scope '/admin' do
    resources :collections
    resources :users do
      get 'edit_password', on: :member
      put 'update_password', on: :member
    end
    resources :orders do
      get 'complete', on: :member
      get 'send_to_client', on: :member
    end
    resources :models, except: :destroy do
      get 'activate', on: :member
      get 'deactivate', on: :member
    end
    resources :brands, except: :destroy do
      get 'search_models', on: :member
      get 'activate', on: :member
      get 'deactivate', on: :member
    end
    resources :products, except: :destroy do
      get 'activate', on: :member
      get 'deactivate', on: :member
      resources :related_products, path: 'related'
      resources :similar_products, path: 'similar'
    end
    resources :pictures, only: [:create, :destroy]
    resources :sliders, only: [:index, :update]
    resources :slider_brands, only: [:index, :update]
    resources :banners, only: [:show, :update], param: :position
    resources :interior_builders, param: :position
    resources :offer_builders
    resources :newsletter_builders
  end
  root 'home#index'
  get 'brand/:id' => 'home#brand_section', as: :brand_section
  get 'marcas' => 'home#brands_section', as: :brands_section
  get 'models/:id' => 'home#model_section', as: :model_section
  get 'colecciones' => 'home#collections_section', as: :collections_section
  get 'coleccion/:id' => 'home#collection_section', as: :collection_section
  get 'lo_mas_nuevo' => 'home#newest_section', as: :newest_section
  get 'producto/:id' => 'home#product_section', as: :product_section
  get 'oferta' => 'home#offer_section', as: :offer_section
  get 'contactanos' => 'home#contact_section', as: :contact_section
  get 'search_section' => 'home#search_section', as: :search_section
  get 'make_contact' => 'home#make_contact', as: :make_contact
  get 'models_for_brand' => 'home#models_for_brand', as: :models_for_brand
  get 'products_for_model' => 'home#products_for_model', as: :products_for_model
  
  resources :newsletters, only: [:create, :index, :destroy]
  resources :customers, only: [:edit, :update]

  resources :carts do
    get 'checkout', on: :member
    get 'detail', on: :member
    get 'complete', on: :member
    resources :line_items
    get 'add_line_item', on: :member
    get 'remove_line_item', on: :member
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 layout 'application'
 before_filter :load_core_objects
 before_filter :load_current_cart

  def index
    @sliders = Slider.includes(:picture).order(:created_at)
    @slider_brand = SliderBrand.first
    @items = @slider_brand.items.includes(:picture)
    @complete_banners = Banner.includes(:picture).complete.order(:position)
    @half_banners = Banner.includes(:picture).half.order(:position)
    @newsletter_builder = NewsletterBuilder.first
  end

  def brands_section
    @models = Model.all
  end

  def brand_section
    @brand = Brand.find(params[:id])
    @products = @brand.products.active
    search_products_based_on_price if params[:product_order].present?
  end

  def model_section
    @model = Model.find(params[:id])
    @products = @model.products.active
    search_products_based_on_price if params[:product_order].present?
  end
  
  def collections_section
    @collections_for_section = Collection.all
  end

  def collection_section
    @collection = Collection.find(params[:id])
    if params[:form_model_id].present?
      @products = active_products.where(collection_id: @collection.id, model_id: params[:form_model_id])
    else
      @products = active_products.where(collection_id: @collection.id)
    end
    @models_for_product= {}
    search_products_based_on_price if params[:product_order].present?
  end

  def newest_section
    @products = active_products.order("products.created_at DESC").limit(20)
    @interior_builders = InteriorBuilder.includes(:picture).order(:position)
    search_products_based_on_price if params[:product_order].present?
  end

  def product_section
    @product = Product.find(params[:id])
    
  end

  def offer_section
    @products = active_products.on_offer
    @offer_builder = OfferBuilder.first
    sort_offer_products if params[:product_order].present?
  end

  def contact_section
  end

  def search_section
    @products = @q.result
    search_products_based_on_price if params[:product_order].present?
  end

  def make_contact
    name = params[:name]
    email = params[:email]
    tel = params[:tel]
    message = params[:message]
    ContactMailer.send_notification_to_admin(name, email, tel, message).deliver_now
    flash[:notice] = "Gracias por contactarnos. Te responderemos pronto"
    redirect_to root_path
  end

  def models_for_brand
    @collection = Collection.find(params[:collection_id])
    @brand = Brand.find(params[:brand_id])
    @models_for_product = @brand.models.map { |model| [model.name.titleize, model.id] }
  end

  def products_for_model
    @collection = Collection.find(params[:collection_id])
    @model = Model.find(params[:model_id])
    @products = Product.where(collection_id: @collection.id, model_id: @model.id)
  end

  private 

  def load_core_objects
    @brands = Brand.active.includes(:models)
    @collections = Collection.all.each_slice(Collection.count / 2)
    @q = Product.active.ransack(params[:q])
  end

  def sort_offer_products
    @products = @products.active.sort_by { |product| product.offer_price } 
    if params[:product_order] == "highest"
      @products.reverse! 
    end
  end

  def search_products_based_on_price
    @products = @products.active.sort_by { |product| product.assigned_price(current_user) }
    if params[:product_order] == "highest"
      @products.reverse! 
    end
  end

  

  def load_current_cart
    if user_signed_in?
      session[:cart_id] = find_or_initialize_cart
      @current_cart ||= Order.find(session[:cart_id])
      @line_item = @current_cart.line_items.build
    end
  end

  def find_or_initialize_cart
    if session[:cart_id].nil?
       order = current_user.orders.create
       session[:cart_id] = order.id
    end
    session[:cart_id]
  end

  def active_products
    Product.joins(:model, :brand).active.merge(Model.active).merge(Brand.active)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def products_order_combo
    [["Highest Price", "highest"], ["Lowest Price", "lowest"]]
  end

  def span_label type
    type == "newest" ? "Nuevo" : "Sale"
  end

  def label_class type
    type == "newest" ? "label" : "label deal-label"
  end

  def image_style picture_path
    if Rails.env.development?
      server_name = ""
    else
      server_name = "http://159.203.192.36/"
    end

    "background: url('" + server_name + picture_path + "') no-repeat center center fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;"
  end

end

app/views/home/_complete_banner_section.html.haml
%section.image-square{class: "#{banner_orientation(banner.position)}"}
  .col-md-6.image.hide-over.bg-oblack
    .background-image-holder.motion-anim
      = image_tag banner.main_picture, alt: "image", class: "background-image"
    .water
      %h3.jfk= banner.hover_title 
      %p.slogan-thumb= banner.hover_description
  .col-md-6.content
    %h3.uppercase
      = banner.title
    %p
      = banner.description
    = link_to banner.link_text, banner.link_url, class: "btn btn-lg bg-dark mb0"

app/views/home/_half_banners_section.html.haml
%section.bg-secondary
  .container
    .row
      - banners.each do |banner|
        .col-sm-6
          = link_to banner.link_url, class: "backstreet" do
            = image_tag banner.main_picture, alt: "pic", class: "mb24"
            .water-bottom
              %h3.jfk-bottom= banner.hover_title 
              %p.slogan-bottom= banner.hover_description
          = link_to banner.link_url do
            %h4.mb8.uppercase= banner.title 
          %p.mb30
            = banner.description

app/views/home/_main_slider_section.html.haml
%section.cover.fullscreen.image-slider.slider-arrow-controls.controls-inside.parallax
  %ul.slides
    - sliders.each do |slider|
      %li.overlay.image-bg.bg-light
        = link_to slider.url_link, class: "anchor-set" do
          .background-image-holder
            = image_tag slider.main_picture, alt: "image", class: "background-image"
          .container.v-align-transform
            .row
              .col-sm-10.col-sm-offset-1.text-center
                %h1.mb40.mb-xs-16.large
                  = slider.title
                %p.lead.mb40
                  = slider.description 
                - unless slider.link_text.blank?
                  %button{class: "btn btn-lg btn-filled lamb"}= slider.link_text 

app/views/home/_navigation_bar.html.haml
.nav-container
  %a#top
  %nav
    .nav-utility
      .wp-info
        %p
          Búscanos en Whatsapp
          %i.fa.fa-whatsapp
          %a{href: "tel:8119166503"} 811 916 6503 
          \/
          %a{href: "tel:8992854904"} 899 285 4904 
    .nav-bar
      .module.left
        = link_to root_path do
          = image_tag("logo.png", alt: "Foundry", class: "logo logo-light")
          = image_tag("logo.png", alt: "Foundry", class: "logo logo-dark")
      .module.widget-handle.mobile-toggle.right.visible-sm.visible-xs.chops
        %i.ti-menu
      .module-group.right
        .module.left
          %ul.menu
            %li.has-dropdown
              = link_to "Mi Teléfono", brands_section_path
              %ul.mega-menu
                - @brands.each do |brand|
                  %li
                    %ul
                      %li
                        %span.title= brand.name.titleize
                        - brand.models.active.each do |model|
                          %li
                            = link_to model.name.titleize, model_section_path(model)
            %li.has-dropdown
              = link_to "Colecciones", collections_section_path
              %ul.mega-menu
                - @collections.each do |collection_slide|
                  %li
                    - collection_slide.each do |collection|
                      %ul
                        %li
                          = link_to collection.name, collection_section_path(collection) 
            %li
              = link_to "Lo más nuevo", newest_section_path
            %li
              = link_to "Oferta", offer_section_path
            %li
              = link_to "Contáctanos", contact_section_path
        / end of menu module
        .module.widget-handle.search-widget-handle.left
          .search
            %i.ti-search
            %span.title Search Site
          .function
            = search_form_for @q, url: search_section_path, class: "search-form" do |f|
              = f.search_field :name_or_description_or_code_cont, placeholder: "Buscar"

        .module.widget-handle.cart-widget-handle.left
          = render 'home/sessions'
        
        - if user_signed_in?
          - if current_user.admin?
            .module.widget-handle.cart-widget-handle.left
              %div
                = link_to products_path do
                  %i.ti-panel
                  %span.title Administrar Sitio
          .module.widget-handle.cart-widget-handle.left.vart#shopping_cart_section
            = render 'home/shopping_cart', order: @current_cart, line_items: @current_cart.line_items

        

app/views/home/_related_products.html.haml
- products.each do |r_product|
  %div.col-md-3.col-sm-4
    %div.image-tile.outer-title.text-center
      = link_to product_section_path(r_product) do
        = image_tag r_product.main_picture, class: "product-thumb"
      %div.title
        %h5= r_product.name
        %div.price-section
          %span{class: "mb8 #{style_for_price(r_product, current_user)}"}= price_for_product(r_product, current_user)
          - if r_product.on_offer && current_user.nil?
            %span.mb.normal-price= number_to_currency(r_product.offer_price, precision: 2)

app/views/home/_select_for_models.html.haml
.select-option
  %i.ti-angle-down
  = select_tag "product_order", options_for_select(models), prompt: "Modelos"

app/views/home/_suscriber_modal.html.haml
.foundry_modal.text-center.image-bg.overlay{"data-cookie" => "signup-form-dismissed", "data-time-delay" => "3000"}
  .background-image-holder
    %img.background-image{:alt => "Background", :src => "img/fitness2.jpg"}/
  %h3.uppercase.bold.italic
    Subscribe and receive Ben's
    %br/
    awesome fitness tips!
  %p.lead.mb48
    This is an auto-show modal that you can customize to appear after a period
    %br/
    of time by editing the 'data-time-delay' attribute.
  %form.form-newsletter.halves.mb160.mb-xs-80{"data-error" => "Please fill all fields correctly.", "data-success" => "Thanks for your registration, we will be in touch shortly."}
    %input.mb0.validate-email.validate-required.signup-email-field{:name => "email", :placeholder => "Email Address", :type => "text"}/
    %button.mb0{:type => "submit"} Keep Me Informed

app/views/home/brand_section.html.haml
%section.page-title.page-title-2.image-bg.overlay.parallax
  %div.background-image-holder
    = image_tag "default-banner.jpg", class: "background-image"

%section.sps
  %div.container
    %div.row
      %div.col-md-6.col-sm-6.masonry-item.col-xs-12
        %div.title
          %h5.ca-colection-title= @brand.name

      %div.col-md-6.col-sm-6.masonry-item.col-xs-12
        %div.select-option
          %i.ti-angle-down
          = form_tag brand_section_path(@brand), id: "products_sort", method: :get, remote: true do
            = select_tag "product_order", options_for_select(products_order_combo), prompt: "Sort by"

    %div.row
      %div.col-sm-12
        %hr
    %div.row.masonry#products_section
      = render 'products', products: @products, type: nil

app/views/home/brand_section.js.erb
$("#products_section").html("<%= escape_javascript(render 'products', products: @products, type: nil) %>")

app/views/home/brands_section.html.haml
%section.sps
  %div.container
    - @brands.each do |brand|
      = render 'brand_section', brand: brand, models: brand.models
    

app/views/home/collection_section.html.haml
%section.page-title.page-title-2.image-bg.overlay.parallax
  %div.background-image-holder
    = image_tag @collection.main_picture, class: "background-image"

%section#products-filters.device-filter
  = hidden_field_tag "collection_id", @collection.id
  .container
    .row
      .col-md-6
        .col-md-12
          .brand-filter
            - @brands.each do |brand|
              %div.brand_sections
                = hidden_field_tag "brand_id", brand.id 
                .checkbox-slide
                  %input.checks{name: "check_brand_#{brand.id}", type: "checkbox", value: "#{brand.id}", id: "check_brand_#{brand.id}"}/
                  %label{for: "check_brand_#{brand.id}"}
                    = image_tag "icon-#{brand.name.downcase}.png"
                  %h6.uppercase.txt-center= brand.name
           
        .col-md-12
          #models_section
            = render 'select_for_models', models: @models_for_product
          
      .col-md-6
        .v-center.ca-instructions
          %h3.mb0.inline-block.uppercase Instrucciones
          %p.lead
            %ul.instt
              %li 1) Elige tu marca
              %li 2) Elige tu modelo
              %li 3) ¡Compra!

%section.sps
  %div.container
    %div.row
      %div.col-md-6.col-sm-6.masonry-item.col-xs-12
        %div.title
          %h5.ca-colection-title= @collection.name

      %div.col-md-6.col-sm-6.masonry-item.col-xs-12
        %div.select-option
          %i.ti-angle-down
          = form_tag collection_section_path, id: "products_sort", method: :get, remote: true do
            = select_tag "product_order", options_for_select(products_order_combo), prompt: "Sort by"
            = hidden_field_tag "form_model_id", nil
           
    %div.row
      %div.col-sm-12
        %hr
    %div.row.masonry#products_section
      = render 'products', products: @products, type: nil

app/views/home/index.html.haml
= render 'main_slider_section', sliders: @sliders
= render 'slider_brands_section', slider_brand: @slider_brand, items: @items
- @complete_banners.each do |banner|
  = render 'complete_banner_section', banner: banner
= render 'third_parties_section'

= render 'half_banners_section', banners: @half_banners

= render 'contact_modal', newsletter_builder: @newsletter_builder

app/views/home/offer_section.html.haml
%section{class: "page-title page-title-2 image-bg", style: "#{image_style(@offer_builder.main_picture)}"}

%section.sps
  %div.container
    %div.row
      %div.col-md-2.col-sm-4.masonry-item.col-xs-12
        %div.select-option
          %i.ti-angle-down
          = form_tag offer_section_path, id: "products_sort", method: :get, remote: true do
            = select_tag "product_order", options_for_select(products_order_combo), prompt: "Sort by"
      
    %div.row
      %div.col-sm-12
        %hr
    %div.row.masonry#products_section
      = render 'products', products: @products, type: "offer"
      

app/views/home/search_section.js.erb
$("#products_section").html("<%= escape_javascript(render 'products', products: @products, type: nil) %>")