config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  scope '/admin' do
    resources :collections
    resources :users do
      get 'edit_password', on: :member
      put 'update_password', on: :member
    end
    resources :orders do
      get 'complete', on: :member
      get 'send_to_client', on: :member
    end
    resources :models, except: :destroy do
      get 'activate', on: :member
      get 'deactivate', on: :member
    end
    resources :brands, except: :destroy do
      get 'search_models', on: :member
      get 'activate', on: :member
      get 'deactivate', on: :member
    end
    resources :products, except: :destroy do
      get 'activate', on: :member
      get 'deactivate', on: :member
      resources :related_products, path: 'related'
      resources :similar_products, path: 'similar'
    end
    resources :pictures, only: [:create, :destroy]
    resources :sliders, only: [:index, :update]
    resources :slider_brands, only: [:index, :update]
    resources :banners, only: [:show, :update], param: :position
    resources :interior_builders, param: :position
    resources :offer_builders
    resources :newsletter_builders
  end
  root 'home#index'
  get 'brand/:id' => 'home#brand_section', as: :brand_section
  get 'marcas' => 'home#brands_section', as: :brands_section
  get 'models/:id' => 'home#model_section', as: :model_section
  get 'colecciones' => 'home#collections_section', as: :collections_section
  get 'coleccion/:id' => 'home#collection_section', as: :collection_section
  get 'lo_mas_nuevo' => 'home#newest_section', as: :newest_section
  get 'producto/:id' => 'home#product_section', as: :product_section
  get 'oferta' => 'home#offer_section', as: :offer_section
  get 'contactanos' => 'home#contact_section', as: :contact_section
  get 'search_section' => 'home#search_section', as: :search_section
  get 'make_contact' => 'home#make_contact', as: :make_contact
  get 'models_for_brand' => 'home#models_for_brand', as: :models_for_brand
  get 'products_for_model' => 'home#products_for_model', as: :products_for_model
  
  resources :newsletters, only: [:create, :index, :destroy]
  resources :customers, only: [:edit, :update]

  resources :carts do
    get 'checkout', on: :member
    get 'detail', on: :member
    get 'complete', on: :member
    resources :line_items
    get 'add_line_item', on: :member
    get 'remove_line_item', on: :member
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_filter :load_core_objects
  before_filter :load_current_cart

  def detail
    @order = Order.find(session[:cart_id]) 
    @line_items = @order.line_items
  end

  def checkout
    @order = Order.find(session[:cart_id])
    @line_items = @order.line_items
  end

  def complete
    @order = Order.find(session[:cart_id])
    @order.update_attribute(:status, "in_progress")
    session[:cart_id] = nil
    flash[:notice] = "Se ha enviado la cotización correctamente"
    OrderMailer.send_confirmation(@order).deliver_now
    redirect_to root_path
  end

  private 

  def load_core_objects
    @brands = Brand.includes(:models)
    @collections = Collection.all.each_slice(Collection.count / 2)
    @q = Product.ransack(params[:q])
  end

  def load_current_cart
    if user_signed_in?
      session[:cart_id] = find_or_initialize_cart
      @current_cart ||= Order.find(session[:cart_id])
      @line_item = @current_cart.line_items.build
    end
  end

  def find_or_initialize_cart
    if session[:cart_id].nil?
       order = current_user.orders.create
       session[:cart_id] = order.id
    end
    session[:cart_id]
  end

end

app/views/carts/_form_line_item.html.haml
= form_for line_item, url: cart_line_item_path(order, line_item), method: :put, remote: true do |f|
  = hidden_field_tag '_method', 'put' 
  %th{scope: "row"}
    = link_to cart_line_item_path(order, line_item), { method: :delete, data: {placement: "top", toggle: "tooltip", confirm: "¿Estás seguro?"}, class: "remove-item"} do
      %i.ti-close
  %td.no-mvl
    = link_to product_section_path(line_item.product) do
      = image_tag line_item.product.main_picture, class: "product-thumb"
  %td
    %span= line_item.product.name
  
  %td
    = f.number_field :quantity, class: "qty-cot mt24 product_quantity", required: true, min: 1
  %td
    %span= price_for_product(line_item.product, current_user)

  %td
    %span{id: "total_#{line_item.id}"}= number_to_currency(line_item.total, precision: 2)

app/views/carts/_price_table.html.haml
%table.table
  %tbody
    %tr
      %th{scope: "row"} Subtotal
      %td= number_to_currency(order.subtotal, precision: 2)
    %tr
      %th{scope: "row"} Total
      %td
        %strong= number_to_currency(order.total, precision: 2)

app/views/carts/checkout.html.haml
%section
  .container
    .row
      .col-md-8.col-md-offset-2.col-sm-10.col-sm-offset-1
        .text-center
          %h4.uppercase Cotización
          %hr
        %table.table.cart.mb48.kart
          %tbody
            %tr
              %th
              %th{:scope => "row"} Producto
              %th.text-center{scope:"row"} Cantidad
              %th.text-center{scope: "row"} Precio
              %th.text-center{scope: "row"} Total

            - @line_items.each do |line_item|
              %tr
                %td.no-mvl
                  = image_tag line_item.product.main_picture, class: "product-thumb"
                %td= line_item.product.name
                %td.text-center= line_item.quantity
                %td.text-center= price_for_product(line_item.product, current_user)
                %td.text-center= number_to_currency(line_item.total, precision: 2)

            %tr
              %th{scope: "row"} Total
              %td
              %td.text-center
                %strong= @line_items.sum(:quantity)
              %td
              %td.text-center
                %strong= number_to_currency(@order.total, precision: 2)
        %form.halves.text-center
          = link_to "Regresar", detail_cart_path(@order), class: "btn-smi"
          = link_to "Enviar Cotización", complete_cart_path(@order), class: "btn-smi"

app/views/carts/detail.html.haml
%section
  .container
    .row
      .col-md-9.col-md-offset-0.col-sm-10.col-sm-offset-1
        - if @line_items.count == 0
          %h5 No tienes ningún producto agregado
        - else
          %table.table.cart.mb48.kart
            %thead
              %tr
                %th &nbsp;
                %th.no-mvl Producto
                %th Descripción
                %th Cantidad
                %th Precio
                %th Total
            %tbody
              - @line_items.each do |line_item|
                %tr{id: "line_item_#{line_item.id}"}
                  = render 'form_line_item', line_item: line_item, order: @order
                
      .col-md-3.col-md-offset-0.col-sm-10.col-sm-offset-1
        .mb24
          %h5.uppercase Tu cotización
          #order_total
            = render 'price_table', order: @order
          
          - if @line_items.count > 0
            = link_to "Cotizar", checkout_cart_path(@order), class: "btn btn-lg mr-hover", id: "checkout_button"