config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  scope '/admin' do
    resources :collections
    resources :users do
      get 'edit_password', on: :member
      put 'update_password', on: :member
    end
    resources :orders do
      get 'complete', on: :member
      get 'send_to_client', on: :member
    end
    resources :models, except: :destroy do
      get 'activate', on: :member
      get 'deactivate', on: :member
    end
    resources :brands, except: :destroy do
      get 'search_models', on: :member
      get 'activate', on: :member
      get 'deactivate', on: :member
    end
    resources :products, except: :destroy do
      get 'activate', on: :member
      get 'deactivate', on: :member
      resources :related_products, path: 'related'
      resources :similar_products, path: 'similar'
    end
    resources :pictures, only: [:create, :destroy]
    resources :sliders, only: [:index, :update]
    resources :slider_brands, only: [:index, :update]
    resources :banners, only: [:show, :update], param: :position
    resources :interior_builders, param: :position
    resources :offer_builders
    resources :newsletter_builders
  end
  root 'home#index'
  get 'brand/:id' => 'home#brand_section', as: :brand_section
  get 'marcas' => 'home#brands_section', as: :brands_section
  get 'models/:id' => 'home#model_section', as: :model_section
  get 'colecciones' => 'home#collections_section', as: :collections_section
  get 'coleccion/:id' => 'home#collection_section', as: :collection_section
  get 'lo_mas_nuevo' => 'home#newest_section', as: :newest_section
  get 'producto/:id' => 'home#product_section', as: :product_section
  get 'oferta' => 'home#offer_section', as: :offer_section
  get 'contactanos' => 'home#contact_section', as: :contact_section
  get 'search_section' => 'home#search_section', as: :search_section
  get 'make_contact' => 'home#make_contact', as: :make_contact
  get 'models_for_brand' => 'home#models_for_brand', as: :models_for_brand
  get 'products_for_model' => 'home#products_for_model', as: :products_for_model
  
  resources :newsletters, only: [:create, :index, :destroy]
  resources :customers, only: [:edit, :update]

  resources :carts do
    get 'checkout', on: :member
    get 'detail', on: :member
    get 'complete', on: :member
    resources :line_items
    get 'add_line_item', on: :member
    get 'remove_line_item', on: :member
  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, presence: true
  has_many :models, dependent: :destroy
  has_many :products, through: :models

  default_scope { order(:name) }

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
end

app/controllers/brands_controller.rb
class BrandsController < AdminController 
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @q = Brand.ransack(params_q)
    @brands = @q.result(distinct: true)
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brands_path, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brands_path, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_models
    @brand = Brand.find(params[:id])
    @models = @brand.models.map { |model| [model.name.titleize, model.id] }
  end

  def activate
    @brand = Brand.find(params[:id])
    @brand.update_attribute(:active, true)
    @brand.models.update_all(active: true)
    @brand.products.update_all(active: true)
    flash[:notice] = "¡Marca activada exitosamente!"
    redirect_to brands_path
  end

  def deactivate
    @brand = Brand.find(params[:id])
    @brand.update_attribute(:active, false)
    @brand.models.update_all(active: false)
    @brand.products.update_all(active: false)
    flash[:notice] = "¡Marca desactivada exitosamente!"
    redirect_to brands_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end

    def params_q
      params[:q] ||= {}
      if params[:q].has_key? :active_false
        params[:q].delete(:active_false)
      else
        params[:q][:active_true] = 1
      end
      params[:q]
    end
    
end

app/helpers/brands_helper.rb
module BrandsHelper

  def brands_combo
    Brand.all.map{ |brand| [brand.name, brand.id] }
  end

  def simplest_brands_combo
    Brand.pluck(:name)
  end

end

app/views/brands/_brands.html.haml
- brands.each do |brand|
  %tr
    %td= brand.id
    %td= brand.name
    %td
      = link_to edit_brand_path(brand), class: "ca-actions" do
        %i.fa.fa-pencil.text-navy
      - if brand.active?
        = link_to deactivate_brand_path(brand), class: "ca-actions" do
          %i.fa.fa-check-circle.text-navy
      - else
        = link_to activate_brand_path(brand), class: "ca-actions" do
          %i.fa.fa-check-circle-o.text-navy

app/views/brands/_form.html.haml
= form_for(@brand) do |f| 
  - if @brand.errors.any? 
    %div#error_explanation
      %h2= pluralize(@brand.errors.count, "error") + "prohibited this brand from being saved:"
      %ul
        - @brand.errors.full_messages.each do |message|
          %li= message

  %div.col-sm-6
    %div.form-group
      = f.text_field :name, placeholder: "Nombre", class: "form-control", required: true

  %div.col-sm-12
    = link_to "Cancelar", brands_path, class: "btn btn-white"
    = f.submit "Guardar Cambios", class: "btn btn-primary ca-suc"

app/views/brands/edit.html.haml
%div.ibox-title
  %h5= "Editar Marca" 

%div.ibox-content.ca-forms-god
  %div.row
    = render 'form'

app/views/brands/index.html.haml
%div.ibox-title
  %h5= "Listado de Marcas"
  = link_to "Nuevo", new_brand_path, class: "btn btn-primary ca-crear"
  
%div.ibox-content
  %div.row
    = search_form_for @q, remote: true do |f|
      %div.col-sm-4.mb-xs
        = f.text_field :name_cont, { placeholder: "Search", class: "input-sm form-control"}
      %div.col-sm-4
        %div.input-group
          %span.input-group-btn
            = f.submit "Buscar", class: "btn btn-sm btn-primary srch" 
      %div.col-sm-4.mb-xs
        %div.bg-shad
          = f.check_box :active_false, {}, "1", nil
          %label Mostrar Inactivos 
      


  %div.table-responsive
    %table.table.table-striped
      %thead
        %th ID
        %th Nombre
        %th Acciones
      %tbody#brands_result
        = render 'brands', brands: @brands
        

app/views/brands/index.js.erb
$("#brands_result").html("<%= escape_javascript(render 'brands', brands: @brands) %>");

app/views/brands/new.html.haml
%div.ibox-title
  %h5= "Nueva Marca" 

%div.ibox-content.ca-forms-god
  %div.row
    = render 'form'

app/views/brands/search_models.js.erb
var models_ids = <%= @models.to_h.to_json.html_safe %>

$("#product_model_id").empty()
$("#product_model_id").append($("<option></option>").attr("value", "").text("Modelo"));
for(var key in models_ids){
  $("#product_model_id").append($("<option></option>").attr("value", models_ids[key]).text(key));
}

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>